linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: false
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: false
    ignore_consecutive: true

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: true
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: false
    convention: ^[a-zA-Z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    order:
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      - content
      - counter-increment
      - counter-reset
      - quotes
      - appearance
      - display
      - float
      - clear
      - flex-flow
      - flex-direction
      - flex-wrap
      - justify-content
      - align-items
      - align-content
      - order
      - flex-grow
      - flex-shrink
      - flex-basis
      - flex
      - align-self
      - overflow
      - overflow-x
      - overflow-y
      - overflow-scrolling
      - scroll-snap-points-y
      - scroll-snap-points-x
      - scroll-snap-type
      - scroll-snap-destination
      - clip
      - box-sizing
      - box-decoration-break
      - width
      - height
      - min-width
      - min-height
      - max-width
      - max-height
      - size
      - resize
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-spacing
      - border-collapse
      - border-width
      - border-style
      - border-color
      - border-top
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left
      - border-left-width
      - border-left-style
      - border-left-color
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-image
      - border-image-source
      - border-image-slice
      - border-image-width
      - border-image-outset
      - border-image-repeat
      - border-top-image
      - border-right-image
      - border-bottom-image
      - border-left-image
      - border-corner-image
      - border-top-left-image
      - border-top-right-image
      - border-bottom-right-image
      - border-bottom-left-image
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - color
      - background
      - background-color
      - background-image
      - background-attachment
      - background-position
      - background-position-x
      - background-position-y
      - background-clip
      - background-origin
      - background-size
      - background-repeat
      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset
      - tap-highlight-color
      - box-decoration-break
      - box-shadow
      - font
      - font-weight
      - font-style
      - font-variant
      - font-size-adjust
      - font-stretch
      - font-size
      - font-family
      - font-feature-settings
      - font-display
      - src
      - text-align
      - text-align-last
      - text-decoration
      - text-decoration-color
      - text-decoration-style
      - text-emphasis
      - text-emphasis-position
      - text-emphasis-style
      - text-emphasis-color
      - text-indent
      - text-justify
      - text-outline
      - text-transform
      - text-wrap
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-size-adjust
      - text-shadow
      - text-rendering
      - letter-spacing
      - line-height
      - vertical-align
      - white-space
      - word-spacing
      - word-wrap
      - word-break
      - tab-size
      - -epub-hyphens
      - hyphens
      - unicode-bidi
      - direction
      - columns
      - column-span
      - column-width
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-rule-width
      - column-rule-style
      - column-rule-color
      - page-break-before
      - break-before
      - page-break-inside
      - break-inside
      - page-break-after
      - break-after
      - orphans
      - widows
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - table-layout
      - caption-side
      - empty-cells
      - visibility
      - opacity
      - interpolation-mode
      - filter
      - cursor
      - pointer-events
      - touch-action
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - zoom
      - max-zoom
      - min-zoom
      - user-zoom
      - orientation
      - transform
      - transform-origin
      - transition
      - transition-delay
      - transition-timing-function
      - transition-duration
      - transition-property
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      - stroke
      - stroke-width
      - stroke-dasharray
      - stroke-dashoffset
      - stroke-linecap
      - fill
      - vector-effect
      - mask
      - clip-path
      - -premailer-width
      - -premailer-cellpadding
      - -premailer-cellspacing

  PropertySpelling:
    extra_properties:
      - font-display

  PropertyUnits:
    enabled: true
    global: ["ch", "em", "ex", "rem", "cm", "in", "mm", "pc", "pt", "px", "q", "vh", "vw", "vmin", "vmax", "deg", "grad", "rad", "turn", "ms", "s", "Hz", "kHz", "dpi", "dpcm", "dppx", "%"]
    properties: {}

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  SelectorFormat:
    enabled: true
    convention: ^[a-z]{1}[a-zA-Z0-9]*(?:-[a-zA-Z0-9]+)*$

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: false
    style: one_space

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: ["hyphens"]

  ZeroUnit:
    enabled: true
